"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _django_tests_running():
    """True when `manage.py test` runs (HTTP client must not hit SECURE_SSL_REDIRECT)."""
    return len(sys.argv) > 1 and sys.argv[1] == 'test'


def _django_render_build_command_running():
    """True for manage.py commands Render runs before the web process starts."""
    if len(sys.argv) < 2:
        return False
    return sys.argv[1] in {
        'collectstatic',
        'migrate',
        'seed_inventory_if_empty',
        'link_static_images_to_products',
        'check',
    }

LOGOUT_REDIRECT_URL = '/'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'


def load_env_file(env_path):
    """Load KEY=VALUE pairs into the process environment.

    Uses assignment (not setdefault) so ``backend/.env`` wins over stale variables
    inherited from the shell or IDE — otherwise SMTP settings in ``.env`` can be
    ignored when ``DJANGO_EMAIL_BACKEND`` was already set to ``console``.
    """
    if not env_path.exists():
        return

    for raw_line in env_path.read_text(encoding='utf-8').splitlines():
        line = raw_line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue

        key, value = line.split('=', 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        os.environ[key] = value


load_env_file(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Render sets RENDER=true. Default DEBUG to False on Render/Railway, True locally.
is_render = os.environ.get('RENDER', '').lower() == 'true'
is_railway = bool(
    os.environ.get('RAILWAY_ENVIRONMENT')
    or os.environ.get('RAILWAY_PROJECT_ID')
    or os.environ.get('RAILWAY_PUBLIC_DOMAIN')
)
is_hosted = is_render or is_railway
debug_default = 'False' if is_hosted else 'True'
DEBUG = os.environ.get('DJANGO_DEBUG', debug_default).lower() in ('1', 'true', 'yes')

# SECURITY WARNING: keep the secret key used in production secret!
DJANGO_SECRET_KEY = (
    os.environ.get('DJANGO_SECRET_KEY', '').strip()
    or os.environ.get('SECRET_KEY', '').strip()
)
if DJANGO_SECRET_KEY:
    SECRET_KEY = DJANGO_SECRET_KEY
elif DEBUG:
    # Stable key in dev so CSRF/session survive runserver restarts (avoids admin logout CSRF 403).
    # Optionally set DJANGO_DEV_SECRET_KEY in .env if multiple developers share a machine.
    SECRET_KEY = os.environ.get(
        'DJANGO_DEV_SECRET_KEY',
        'django-insecure-kistie-dev-only-rotate-for-shared-machines',
    )
elif is_hosted and _django_render_build_command_running():
    # Hosted build steps run before runtime secrets are always available.
    SECRET_KEY = 'hosted-build-phase-only-not-used-at-runtime'
else:
    raise ImproperlyConfigured(
        'Set DJANGO_SECRET_KEY when DEBUG=False (production / staging). '
        'On Render or Railway, add DJANGO_SECRET_KEY to the web service environment.'
    )
enable_admin_default = 'False' if is_hosted else 'True'
ENABLE_ADMIN = os.environ.get('DJANGO_ENABLE_ADMIN', enable_admin_default).lower() in ('1', 'true', 'yes')

allowed_hosts_raw = (
    os.environ.get('ALLOWED_HOSTS')
    or os.environ.get('DJANGO_ALLOWED_HOSTS')
    or '.onrender.com .railway.app .up.railway.app localhost 127.0.0.1'
)
ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_raw.replace(',', ' ').split() if host.strip()]

if is_railway:
    for _railway_host in ('.railway.app', '.up.railway.app', 'healthcheck.railway.app'):
        if _railway_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_railway_host)

# Render provides the public hostname for each service. Trust it automatically.
render_external_hostname = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '').strip()
if render_external_hostname and render_external_hostname not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(render_external_hostname)

# Railway sets RAILWAY_PUBLIC_DOMAIN on each web service.
railway_public_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '').strip()
if railway_public_domain and railway_public_domain not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(railway_public_domain)

CSRF_TRUSTED_ORIGINS = []
if render_external_hostname:
    CSRF_TRUSTED_ORIGINS.append(f'https://{render_external_hostname}')
if railway_public_domain:
    CSRF_TRUSTED_ORIGINS.append(f'https://{railway_public_domain}')
for _raw in os.environ.get('CSRF_TRUSTED_ORIGINS', '').replace(',', ' ').split():
    _origin = _raw.strip()
    if _origin and _origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_origin)
if DEBUG:
    for _local in (
        'http://127.0.0.1:8000',
        'http://localhost:8000',
        'http://127.0.0.1:5173',
        'http://localhost:5173',
    ):
        if _local not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(_local)

EMAIL_BACKEND = os.environ.get('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'localhost').strip()
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '25'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '').strip()
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Google displays app passwords as four groups; SMTP expects one continuous string.
if EMAIL_HOST == 'smtp.gmail.com' and EMAIL_HOST_PASSWORD:
    EMAIL_HOST_PASSWORD = ''.join(EMAIL_HOST_PASSWORD.split())
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'False').lower() in ('1', 'true', 'yes', 'on')
DEFAULT_FROM_EMAIL = os.environ.get('DJANGO_DEFAULT_FROM_EMAIL', 'noreply@eastafricafashion.local')
CONTACT_RECIPIENT_EMAIL = os.environ.get('CONTACT_RECIPIENT_EMAIL', 'dallas8000@gmail.com')
SITE_URL = os.environ.get('SITE_URL', 'https://kristie-store.onrender.com').strip()
WHATSAPP_STORE_NUMBER = os.environ.get('WHATSAPP_STORE_NUMBER', '256704757198').strip()
ORDER_ALERT_EMAIL = os.environ.get('ORDER_ALERT_EMAIL', CONTACT_RECIPIENT_EMAIL).strip()
STORE_ADDRESS = os.environ.get(
    'STORE_ADDRESS',
    'Prime Complex Building, Wilson Street, Shop No. C-03, Kampala, Uganda',
).strip()
# Override on Render/local with your real profile URL if the handle differs.
INSTAGRAM_PROFILE_URL = os.environ.get(
    'INSTAGRAM_PROFILE_URL',
    'https://www.instagram.com/kistie_storeug/',
).strip()
SERPAPI_API_KEY = os.environ.get('SERPAPI_API_KEY', '').strip()
PRICE_SCAN_UGX_RATE = os.environ.get('PRICE_SCAN_UGX_RATE', '3700').strip()
PRICE_SCAN_SITE_BASE_URL = os.environ.get('PRICE_SCAN_SITE_BASE_URL', '').strip()

# AI features — set either key (or both) to enable. AI_PROVIDER controls which is used first.
_raw_ai_provider = os.environ.get('AI_PROVIDER', 'openai').strip().lower()
if _raw_ai_provider.startswith('gemini'):
    AI_PROVIDER = 'gemini'
elif _raw_ai_provider.startswith('openai'):
    AI_PROVIDER = 'openai'
else:
    AI_PROVIDER = _raw_ai_provider
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '').strip()
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', '').strip()
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini').strip()
GEMINI_MODEL = os.environ.get('GEMINI_MODEL', 'gemini-2.0-flash').strip()
# Pesapal handoff: Node payments service URL (local dev default). Set on Render to your deployed payments base + path.
PESAPAL_INITIATE_URL = os.environ.get(
    'PESAPAL_INITIATE_URL',
    'http://127.0.0.1:5000/api/pay/pesapal',
).strip()


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'inventory',
    'cart',
    'pages',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.admin_gate.AdminSuperuserOnlyMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
if DEBUG:
    # Dev-only CORS for Vite/React on :5173 calling /api/ — not active in production.
    MIDDLEWARE.insert(2, 'core.dev_cors.DevCorsMiddleware')

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'core' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context.feature_flags',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Override with DATABASE_URL when present (Render / Railway PostgreSQL, etc.)
_database_url = os.environ.get('DATABASE_URL')
if _database_url:
    _db_kwargs = {'conn_max_age': 600}
    if _database_url.startswith('postgres://'):
        _database_url = 'postgresql://' + _database_url[len('postgres://') :]
    # Railway private Postgres (*.railway.internal) does not use the same SSL path as public URLs.
    if 'railway.internal' in _database_url:
        if 'sslmode=' not in _database_url:
            _database_url += '&sslmode=disable' if '?' in _database_url else '?sslmode=disable'
        _db_kwargs['ssl_require'] = False
    elif 'railway' in _database_url:
        if 'sslmode=' not in _database_url:
            _database_url += '&sslmode=require' if '?' in _database_url else '?sslmode=require'
        _db_kwargs['ssl_require'] = not DEBUG
    else:
        _db_kwargs['ssl_require'] = not DEBUG
    DATABASES['default'] = dj_database_url.parse(_database_url, **_db_kwargs)
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS'].setdefault('connect_timeout', 10)


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# LocMem cache used for login attempt throttling (no extra services required).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'kistie-store',
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'core' / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# Manifest storage needs collectstatic; use plain storage under `manage.py test` (CI).
if _django_tests_running():
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (user-uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework — secure defaults; inventory viewsets use StaffOrReadOnly for writes.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '2000/hour',
    },
}

# --- Production TLS / cookies (Render, Railway, etc. terminate TLS and set X-Forwarded-Proto) ---
if not DEBUG and not _django_tests_running():
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    USE_X_FORWARDED_HOST = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Railway probes /health/ over plain HTTP inside the container; SSL redirect fails the check.
    SECURE_SSL_REDIRECT = not is_railway
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    _hsts_raw = os.environ.get('DJANGO_HSTS_SECONDS', '').strip()
    if _hsts_raw.isdigit():
        SECURE_HSTS_SECONDS = int(_hsts_raw)
        SECURE_HSTS_INCLUDE_SUBDOMAINS = (
            os.environ.get('DJANGO_HSTS_INCLUDE_SUBDOMAINS', 'False').lower() in ('1', 'true', 'yes')
        )
        SECURE_HSTS_PRELOAD = (
            os.environ.get('DJANGO_HSTS_PRELOAD', 'False').lower() in ('1', 'true', 'yes')
        )

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}
