# Generated by Django 5.2.13 on 2026-08-09 12:35

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('bill_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('paid', 'Paid'), ('void', 'Void')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Account payable',
                'verbose_name_plural': 'Accounts payable',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=40)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('partial', 'Partial'), ('paid', 'Paid'), ('void', 'Void')], default='open', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Account receivable',
                'verbose_name_plural': 'Accounts receivable',
                'ordering': ['-invoice_date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('household', 'Household'), ('business_operational', 'Business operations'), ('business_rent', 'Rent / utilities'), ('business_staff', 'Staff'), ('business_marketing', 'Marketing'), ('other', 'Other')], default='other', max_length=32)),
                ('sub_category', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mobile_money', 'Mobile money'), ('bank_transfer', 'Bank transfer'), ('credit', 'Credit')], default='cash', max_length=32)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('bill_number', models.CharField(blank=True, max_length=120)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('open', 'Open'), ('partial', 'Partial'), ('overdue', 'Overdue')], default='paid', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImportShipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('source_country', models.CharField(blank=True, max_length=100)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_arrival', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('in_transit', 'In transit'), ('received', 'Received'), ('stored', 'In store')], default='ordered', max_length=32)),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('import_duty', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Import shipment',
                'verbose_name_plural': 'Import shipments',
                'ordering': ['-order_date'],
            },
        ),
    ]
